### PR TITLE
Customer io pushes

### PR DESCRIPTION
**Pull request by sampettersson**
Register push tokens in Customer IO instead of Firebase

### CODE REVIEW

**Comment by sampettersson** [comment]
Add a listener for has token

**Review by sladan-hedvig — APPROVED** [review]
I tried to send myself notification after registering thought chat but never received it 🐹 
Others we are sending to BE when we have it 👍

**Comment by sampettersson** [comment]
@sladan-hedvig just to make sure:

1. Push permissions was accepted
2. You where using a Release build on a physical device (TestFlight works fine, but not a local debug build that goes to the APNS sandbox)
3. The app wasn't in the foreground

If it still fails after all of these are fulfilled please let me know.

**Comment by sladan-hedvig** [comment]
@sampettersson  I used debug version. I guess thats the issue ^^

**Comment by sladan-hedvig** [comment]
Its working! Awesome!

**Pull request merged**
