### PR TITLE
GEN-1420: Payment history view

### PR DESCRIPTION
**Pull request by sladan-hedvig**
- Added payment history view

## Checklist

- [ ] Dark/light mode verification
- [ ] Landscape verification
- [ ] iPad verification
- [ ] iPod/iPhone 12 mini/iPhone SE verification

### CODE REVIEW

**Review by julia-andersson — COMMENTED** [review]
Screenshot 2023-11-10 at 13 11 31

Do we have this info card on bottom?

**Review by julia-andersson — CHANGES_REQUESTED** [review]
simulator_screenshot_9F5E21F9-71BB-4FBA-9F9D-7E1EFA15560D
Background color for title is off

**Comment by sladan-hedvig** [comment]
> Screenshot 2023-11-10 at 13 11 31
> Do we have this info card on bottom?

Added now :S forgot about it

**Comment by sladan-hedvig** [comment]
> simulator_screenshot_9F5E21F9-71BB-4FBA-9F9D-7E1EFA15560D Background color for title is off

Nice catch, fixed now

**Review by julia-andersson — APPROVED** [review]

**Pull request merged**
